# Generated by Django 2.1.5 on 2019-03-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0003_auto_20190210_2346'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('semester', 'course', 'section_name')},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('last_name', 'first_name', 'nickname')},
        ),
    ]
