# Generated by Django 2.1.5 on 2019-03-23 20:22

from django.db import migrations, models

period_sequence = [(10, 'Spring'), (20, 'Summer'), (30, 'Fall'), (9999, 'TemporaryVale')]

PERIODS = [
    {'period_sequence': period_sequence[i][0], 'period_name':period_sequence[i][1]} for i in range(len(period_sequence))
]



def add_period_data(apps, schema_editor):
    period_model_class = apps.get_model('courseinfo', 'Period')
    for period in PERIODS:
        period_object = period_model_class.objects.create(
            period_sequence=period['period_sequence'],
            period_name=period['period_name'],
        )


def remove_period_data(apps, schema_editor):
    period_model_class = apps.get_model('courseinfo', 'Period')
    for period in PERIODS:
        period_object = period_model_class.objects.get(
            period_sequence=period['period_sequence'],
        )
        period_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0005_semester_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_sequence', models.IntegerField(unique=True)),
                ('period_name', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['period_sequence'],
            },
        ),

        migrations.RunPython(
            add_period_data,
            remove_period_data
        ),

    ]
